spring:
  application:
    name: customer-service

  zipkin:
    service:
      name: customer-service

  data:
    mongodb:
      uri: mongodb://mngadmin:alae.2001@localhost:27017/ecommerce?authMechanism=SCRAM-SHA-1&authSource=admin
      database: customer


customer:
  params:
    x: 40
    y: 30

server:
  port: 9000
