spring:
  application:
    name: customer-service

  zipkin:
    service:
      name: customer-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce

customer:
  params:
    x: 40
    y: 30

server:
  port: 9000
