spring:
  application:
    name: gateway-service

  zipkin:
    service:
      name: gateway-service

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

gateway:
  params:
    xx: 888836
    yy: 9999

server:
  port: 8888
