spring:
  application:
    name: notification-service

  zipkin:
    service:
      name: notification-service

  data:
    mongodb:
      uri: mongodb://mngadmin:alae.2001@localhost:27017/ecommerce?authMechanism=SCRAM-SHA-1&authSource=admin
      database: notification
      # MongoDB URI for connecting



notification:
  params:
    a: 1
    e: 3

server:
  port: 9002
